name: CI

env:
  CI: true

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
